### ISSUE TITLE
FloorIT.java

### ISSUE THREAD

**Issue by farr3ll024** [farr3ll024/oct31#7]
Just wanted to ask about a very small error that is preventing compilation. I commented out lines 72-73 in FloorIT.java; It looks like the method that is used is either misspelled or hasn't been written. 

Should this be a different method name? Or is that method still in production?  
       // int result = instance.getShelfLimit(); 

Everything else looks great! I like the point system that you added to Floor.java, I think it will help a lot with creating the visualizer.

**Comment by tfinley521** [comment]
Oh yeah...I kind of was lazy and made every method static.  So you don't put instance.getShelfLimit(), you just call getShelfLimit() on its own.  So to fix your code, just do 
int result = getShelfLimit();
And it should work fine.  Lemme know if you have further problems.

**Comment by tfinley521** [comment]
Oh, also I noticed you were instantiating a Floor class variable.  I haven't bothered implementing a constructor method in my Floor class, it didn't really seem necessary at the time.  We can go over details on Friday I guess about whether or not I need to use it.

**Comment by farr3ll024** [comment]
sounds good! Yeah, I wasn't sure what all would need to be instantiated/what parameters to send in so I just added those parts to master as a comment. Would you prefer I send an email next time(if I end up having another question) instead of posting the issue? or do you like getting the issue on github?

**Comment by tfinley521** [comment]
Nah it doesn't matter, my e-mail notifies me of these anyway.
